UPDATE CqlDemo.MyCounter SET cval=cval+1 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;
UPDATE CqlDemo.MyCounter SET cval=cval+2 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;  
UPDATE CqlDemo.MyCounter SET cval=cval+3 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;
UPDATE CqlDemo.MyCounter SET cval=cval+4 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;
UPDATE CqlDemo.MyCounter SET cval=cval+5 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;
UPDATE CqlDemo.MyCounter SER cval=cval+6 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;
UPDATE CqlDemo.MyCounter SET cval=cval+7 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82; 
UPDATE CqlDemo.MyCounter SET cval=cval+8 WHERE id=44a2054c-f98b-43a7-833d-0e1358fdaa82;
